### ISSUE TITLE
Update Readme File

### ISSUE THREAD

**Issue by KRISHNASAIRAJ** [KRISHNASAIRAJ/Hacktoberfest-2022#1]

**Comment by rohitkori** [comment]
can you please assign it to me?

**Comment by GunaVarshith** [comment]
I would like to work on this issue.Please assign this to me.

**Comment by KRISHNASAIRAJ** [comment]
> I would like to work on this issue.Please assign this to me.

Ok please do it accurately

**Comment by lasyapriya-p** [comment]
Please assign this issue to me

**Comment by KRISHNASAIRAJ** [comment]
> Please assign this issue to me

yeah go ahead

**Comment by KRISHNASAIRAJ** [comment]
Thanks for your contribution
