### ISSUE TITLE
Create a Sports Entry System And A Readme File for it

### ISSUE THREAD

**Issue by KRISHNASAIRAJ** [KRISHNASAIRAJ/Hacktoberfest-2022#11]

**Comment by lasyapriya-p** [comment]
please assign it to me

**Comment by KRISHNASAIRAJ** [comment]
Please add display and other required functions

**Comment by lasyapriya-p** [comment]
> Please add display and other required functions

yeah sure

**Comment by KRISHNASAIRAJ** [comment]
Thanks for your contribution.Keep Coding!
