### ISSUE TITLE
Create A Countdown Timer Using Python

### ISSUE THREAD

**Issue by KRISHNASAIRAJ** [KRISHNASAIRAJ/Hacktoberfest-2022#2]

**Comment by GitArya27** [comment]
please assign me this issue @KRISHNASAIRAJ

**Comment by GunaVarshith** [comment]
I would like to work on this.Please assign this to me.

**Comment by KRISHNASAIRAJ** [comment]
> I would like to work on this.Please assign this to me.

yeah go ahead

**Comment by KRISHNASAIRAJ** [comment]
Please add function to pause and close application

**Comment by GunaVarshith** [comment]
> Please add function to pause and close application

Yeah,Sure!Please Assign to me

**Comment by KRISHNASAIRAJ** [comment]
> > Please add function to pause and close application
> 
> Yeah,Sure!Please Assign to me

already assigned
