### ISSUE TITLE
Create virtual learning assistant using c program

### ISSUE THREAD

**Issue by KRISHNASAIRAJ** [KRISHNASAIRAJ/Hacktoberfest-2022#7]

**Comment by GunaVarshith** [comment]
I would like to work on this issue.Please assign this to me.

**Comment by KRISHNASAIRAJ** [comment]
> I would like to work on this issue.Please assign this to me.

yeah go ahead

**Comment by KRISHNASAIRAJ** [comment]
@GunaVarshith Please add login system to it

**Comment by GunaVarshith** [comment]
> @GunaVarshith Please add login system to it

Yeah,Sure!

**Comment by KRISHNASAIRAJ** [comment]
Thanks for your work
